### ISSUE TITLE
hello WisZhou

### ISSUE THREAD

**Issue by HelloYie** [WisZhou/kick_children_ass_together#1]
RT. This project is not cool.

**Comment by HelloYie** [comment]
发哥，之前不是问过我除了bootstrap之外的，自适应desktop和mobile的前端样式库吗，这里推荐几个我使用过的：
 
### 自适应响应类：
+ [sematic UI](http://semantic-ui.com/)， sematicOrg开发的，特点是语义化，跟bootstrap很类似。
+ [pure css](http://purecss.io/)  雅虎开发的，特点是小，纯净，易改造。

### 两个专注响应布局的，不提供组件
+ https://golden-layout.com/ 方便集成react， 不过不提供.
+ http://susy.oddbird.net/  专注grid layout

### 非响应类，但是非常清新好看
+ http://www.material-ui.com/#/  谷歌 material 设计，有成熟的react组件
+ [蚂蚁金服 ui](http://ant.design/)  支付宝团队开发的react组件，很漂亮

### 专注手机上的展示
+ http://goratchet.com/  模拟原生app样式的html ui
+ https://github.com/weui/weui  微信官方的html5应用ui 
+ http://ionicframework.com/  可以用来开发基于webview嵌入的混合式手机app

**Comment by WisZhou** [comment]
gotcha
